version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_SERVER_API_URL=http://localhost:8080/api
    depends_on:
      - backend
