version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8081:8081"
    environment:
      - PORT=8081

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_SERVER_API_URL=http://localhost/api
    depends_on:
      - backend
